// ============================================================================
// ⚡ src/runtime.ts - 运行时代码模板（字符串）
// ============================================================================
export const runtimeTemplate = `// 🚀 Auto-generated by vite-plugin-preloader
(function() {
  'use strict';
  
  // 🎯 预加载配置（构建时注入）
  const PRELOAD_ROUTES = __PRELOAD_ROUTES__
  const PRELOAD_OPTIONS = __PRELOAD_OPTIONS__

  class PreloaderManager {
    constructor() {
      this.preloadedRoutes = new Set()
      this.isPreloading = false
      this.stats = {
        total: 0, completed: 0, failed: 0, startTime: 0, endTime: 0
      }
      this.statusElement = null
    }

    async start() {
      if (this.isPreloading) return

      this.isPreloading = true
      this.stats = {
        total: PRELOAD_ROUTES.length,
        completed: 0, failed: 0,
        startTime: Date.now(), endTime: 0
      }

      if (PRELOAD_OPTIONS.debug) {
        console.log(\`🚀 [预加载] 开始预加载 \${PRELOAD_ROUTES.length} 个页面\`)
      }

      // 显示状态指示器
      this.showStatus()

      const sortedRoutes = [...PRELOAD_ROUTES].sort((a, b) => a.priority - b.priority)
      
      for (const route of sortedRoutes) {
        await this.preloadSingle(route)
        this.updateStatus()
        await this.sleep(100)
      }

      this.stats.endTime = Date.now()
      this.isPreloading = false
      
      if (PRELOAD_OPTIONS.debug) {
        console.log(\`🎉 [预加载] 完成! 耗时 \${this.stats.endTime - this.stats.startTime}ms\`)
      }

      // 隐藏状态指示器
      this.hideStatus()
    }

    async preloadSingle(route) {
      if (this.preloadedRoutes.has(route.path)) return

      try {
        const startTime = Date.now()
        // 使用 eval 来动态执行导入函数字符串
        const importFn = eval('(' + route.component + ')')
        await importFn()
        const loadTime = Date.now() - startTime
        
        this.preloadedRoutes.add(route.path)
        this.stats.completed++
        
        if (PRELOAD_OPTIONS.debug) {
          console.log(\`✅ [预加载] \${route.path} (\${loadTime}ms) - \${route.reason}\`)
        }
      } catch (error) {
        this.stats.failed++
        if (PRELOAD_OPTIONS.debug) {
          console.error(\`❌ [预加载] \${route.path} 失败:\`, error)
        }
      }
    }

    showStatus() {
      if (!PRELOAD_OPTIONS.showStatus || !document.body) return

      // 添加样式
      if (!document.getElementById('preloader-styles')) {
        const style = document.createElement('style')
        style.id = 'preloader-styles'
        const position = PRELOAD_OPTIONS.statusPosition.replace('-', ': 20px; ') + ': 20px;'
        style.textContent = \`
          .preloader-status {
            position: fixed; \${position}
            background: rgba(0,0,0,0.8); color: white; padding: 8px 16px;
            border-radius: 6px; font-size: 12px; z-index: 9999;
            pointer-events: none; font-family: system-ui;
            transition: opacity 0.3s ease;
          }
          .preloader-status.fade-out {
            opacity: 0;
          }
        \`
        document.head.appendChild(style)
      }

      // 创建状态元素
      this.statusElement = document.createElement('div')
      this.statusElement.className = 'preloader-status'
      this.updateStatus()
      document.body.appendChild(this.statusElement)
    }

    updateStatus() {
      if (!this.statusElement) return
      this.statusElement.textContent = \`🔄 正在优化页面... \${this.stats.completed}/\${this.stats.total}\`
    }

    hideStatus() {
      if (!this.statusElement) return
      this.statusElement.classList.add('fade-out')
      setTimeout(() => {
        if (this.statusElement && this.statusElement.parentNode) {
          this.statusElement.parentNode.removeChild(this.statusElement)
        }
      }, 300)
    }

    sleep(ms) {
      return new Promise(resolve => setTimeout(resolve, ms))
    }

    isPreloaded(path) {
      return this.preloadedRoutes.has(path)
    }

    getStats() {
      return {
        ...this.stats,
        preloadedPaths: Array.from(this.preloadedRoutes),
        isPreloading: this.isPreloading
      }
    }
  }

  // 🚀 全局实例
  const preloader = new PreloaderManager()

  // 🛠️ 开发环境调试工具
  if (PRELOAD_OPTIONS.debug) {
    window.preloaderDebug = {
      stats: () => preloader.getStats(),
      restart: () => preloader.start(),
      check: (path) => preloader.isPreloaded(path),
      help: () => console.log('🛠️ 预加载调试: stats() | restart() | check(path)')
    }
    console.log('🛠️ 预加载调试工具: window.preloaderDebug')
  }

  // 🚀 自动启动 - 等待 DOM 加载完成
  function autoStart() {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => {
        setTimeout(() => preloader.start(), PRELOAD_OPTIONS.delay)
      })
    } else {
      setTimeout(() => preloader.start(), PRELOAD_OPTIONS.delay)
    }
  }

  // 立即执行自动启动
  autoStart()

  // 导出到全局（可选使用）
  window.usePreloader = () => ({
    start: () => preloader.start(),
    isPreloaded: (path) => preloader.isPreloaded(path),
    getStats: () => preloader.getStats()
  })

})();`